[project]
name = "quads-tui"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
run = "python app.py"

[dependencies]
python = "3.12.*"
xarray = "*"
pandas = "*"
pip = "*"
pyyaml = "*"
dask = "*"
netCDF4 = "*"
h5netcdf = "*"
py-spy = ">=0.4.2,<0.5"
duckdb = ">=0.10.0"
pyarrow = ">=15.0.0"

[pypi-dependencies]
textual = "*"
textual-plotext = "*"
